Fix PostgreSQL health check in health.go
- Replace h.container.Ent.DB().PingContext() with proper Ent query
- Use h.container.Ent.User.Query().Limit(1).Count(ctx) to check PostgreSQL
- Ent Client doesn't have DB() method, need to use Ent queries instead
- Fixed both Readiness() and Health() methods

This fixes the compilation error:
  internal\handlers\health.go:50:28: h.container.Ent.DB undefined